### ISSUE TITLE
Node has invalid binary format

### ISSUE THREAD

**Issue by anmay** [wiomoc/whatsappweb-rs#6] opened 2018-07-13 17:55 UTC
I am facing below issue, Please check it.

```
2018-07-13 20:52:53 INFO  [presence] new state: Connected
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("Node has invalid binary format"), State { next_error: Some(Error(Msg("Couldn\'t read node content (list), node decription: response"), State { next_error: Some(Error(Msg("Couldn\'t read list item: 529, size: 4354"), State { next_error: Some(Error(Io(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', libcore/result.rs:945:5
```

**Comment by edantie** [comment] 2018-09-10 13:26
The problem is in node_wire.rs, line 414
for some reason tag may be a LIST_16
Hope that help...

**Comment by wiomoc** [comment] 2018-09-10 20:19
@anmay @edantie The problem is caused by the wrong endian in https://github.com/wiomoc/whatsappweb-rs/blob/c4ceba4b106ce86c9944e49023f9233219b25080/src/node_wire.rs#L122

**Comment by wiomoc** [comment] 2018-09-10 20:24
Should be fixed on master

**Comment by edantie** [comment] 2018-09-11 06:32
Working for me!

**Closed** 2018-10-06 12:47 UTC
